const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_FAILED: 'SIGNIN_FAILED',
   
};

export default UserActionTypes;