const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_FAILED: 'SIGNIN_FAILED',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILED: 'SIGN_OUT_FAILED',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILED: 'SIGN_UP_FAILED'
   
};

export default UserActionTypes;